version: '3'

services:
  ui:
    build: 
      context: .
      #dockerfile: docker/Dockerfile
      args:
        BUILD_DATE: "today"
        VERSION: "nginx version"
        VCS_REF: "na"
    user: nginx
    tmpfs:
      - /usr/share/nginx/html
      - /etc/nginx/conf.d
      - /tmp
    read_only: true
    environment:
      URL_ALLURE_API: "http://localhost:5050"
      URL_PREFIX: "/system/tests/"
    ports:
      - "7474:8080"

  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 12
      # SECURITY_USER: my_username
      # SECURITY_PASS: my_password
      # SECURITY_VIEWER_USER: "view_user"
      # SECURITY_VIEWER_PASS: "view_pass"
      # SECURITY_ENABLED: 1
      # MAKE_VIEWER_ENDPOINTS_PUBLIC: 0
      #URL_PREFIX: /my-prefix
      #ACCESS_TOKEN_EXPIRES_IN_SECONDS: 10
      #REFRESH_TOKEN_EXPIRES_IN_SECONDS: 10
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/projects:/app/projects
